export default {
    ITEMS: [
        '2x4',
        'Amplifier',
        'Baseball Bat',
        'Battery',
        'Beer',
        'Bingo Ball Cage',
        'Blast Frequency Gun',
        'Bowie Knife',
        'Box of Nails',
        'Boxing Gloves',
        'Bucket',
        'Bull Skull',
        'Cement Saw',
        'Chainsaw',
        'Computer Case',
        'Construction Hat',
        'Drill Motor',
        'Dynamite',
        'Electric Chair',
        'Electric Guitar',
        'Fire Axe',
        'Fire Extinguisher',
        'Flashlight',
        'Football',
        'Fountain Firework',
        'Gasoline Canister',
        'Gems',
        'Goblin Mask',
        'Grenade',
        'Hunk of Meat',
        'Lawn Dart',
        'Lawn Mower',
        'Leaf Blower',
        'Leaf Rake',
        'Lizard Mask',
        'Lead Pipe',
        'LMG',
        'MMA Gloves',
        'Machete',
        'Merc Assault Rifle',
        'Motor Oil',
        'Nectar',
        'Newspaper',
        'Paddle',
        'Parasol',
        'Pitchfork',
        'Plates',
        'Power Drill',
        'Propane Tank',
        'Push Broom',
        'Pylon',
        'Queen',
        'Robot Bear',
        'Rocket Fireworks',
        'Saw Blade',
        'Servbot Mask',
        'Shotgun',
        'Sledge Hammer',
        'Spear',
        'Spray Paint',
        'Tennis Racquet',
        'Tiki Torch',
        'Toy Helicopter',
        'Toy Spitball Gun',
        'Training Sword',
        'Vacuum Cleaner',
        'Water Gun',
        'Wheelchair',
        'Whiskey',
    ],
    COMBO_CARDS: [
        { name: 'Drill Bucket', image: 'comboc_drillbucket_result.png', items: ['Bucket', 'Power Drill'] },
        { name: 'I.E.D.', image: 'comboc_ied_result.png', items: ['Box of Nails', 'Propane Tank'] },
        { name: 'Molotov', image: 'comboc_molotov_result.png', items: ['Newspaper', 'Whiskey'] },
        { name: 'Pole Weapon', image: 'comboc_poleweapon_result.png', items: ['Machete', 'Push Broom'] },
        { name: 'Air Horn', image: 'comboc_airhorn_result.png', items: ['Pylon', 'Spray Paint'] },
        { name: 'Gem Blower', image: 'comboc_gemblower_result.png', items: ['Gems', 'Leaf Blower'] },
        { name: 'Fountain Lizard', image: 'comboc_fountainlizard_result.png', items: ['Fountain Firework', 'Lizard Mask'] },
        { name: 'Hacker', image: 'comboc_hacker_result.png', items: ['Computer Case', 'Flashlight'] },
        { name: 'Ripper', image: 'comboc_ripper_result.png', items: ['Cement Saw', 'Saw Blade'] },
        { name: 'Electric Chair', image: 'comboc_electrocutionchair_result.png', items: ['Battery', 'Wheelchair'] },
        { name: 'Flaming Gloves', image: 'comboc_flaminggloves_result.png', items: ['Boxing Gloves', 'Motor Oil'] },
        { name: 'Flamethrower', image: 'comboc_flamethrower_result.png', items: ['Water Gun', 'Gasoline Canister'] },
        { name: 'Heliblade', image: 'comboc_heliblade_result.png', items: ['Machete', 'Toy Helicopter'] },
        { name: 'Fire Spitter', image: 'comboc_firespitter_result.png', items: ['Toy Spitball Gun', 'Tiki Torch'] },
        { name: 'Beer Hat', image: 'comboc_beerhat_result.png', items: ['Beer', 'Construction Hat'] },
        { name: 'Sticky Bomb', image: 'comboc_stickybomb_result.png', items: ['Lawn Dart', 'Dynamite'] },
        { name: 'Driller', image: 'comboc_driller_result.png', items: ['Power Drill', 'Spear'] },
        { name: 'Defiler', image: 'comboc_defiler_result.png', items: ['Fire Axe', 'Sledge Hammer'] },
        { name: 'Holy Arms', image: 'comboc_holyarms_result.png', items: ['Training Sword', 'Box of Nails'] },
        { name: 'Hail Mary', image: 'comboc_hailmary_result.png', items: ['Football', 'Grenade'] },
        { name: 'Freedom Bear', image: 'comboc_freedombear_result.png', items: ['Robot Bear', 'LMG'] },
        { name: 'Freezer Bomb', image: 'comboc_freezerbomb_result.png', items: ['Dynamite', 'Fire Extinguisher'] },
        { name: 'Knife Gloves', image: 'comboc_knifegloves_result.png', items: ['Boxing Gloves', 'Bowie Knife'] },
        { name: 'Roaring Thunder', image: 'comboc_roaringthunder_result.png', items: ['Battery', 'Goblin Mask'] },
        { name: 'Super Slicer', image: 'comboc_superslicer_result.png', items: ['Servbot Mask', 'Lawn Mower'] },
        { name: 'Handy Chipper', image: 'comboc_handychipper_result.png', items: ['Lawn Mower', 'Wheelchair'] },
        { name: 'Dynameat', image: 'comboc_dynameat_result.png', items: ['Dynamite', 'Hunk of Meat'] },
        { name: 'Electric Rake', image: 'comboc_electricrake_result.png', items: ['Battery', 'Leaf Rake'] },
        { name: 'Paddlesaw', image: 'comboc_paddlesaw_result.png', items: ['Paddle', 'Chainsaw'] },
        { name: 'Parablower', image: 'comboc_parablower_result.png', items: ['Leaf Blower', 'Parasol'] },
        { name: 'Rocket Launcher', image: 'comboc_rocketlauncher_result.png', items: ['Rocket Fireworks', 'Lead Pipe'] },
        { name: 'Boomstick', image: 'comboc_boomstick_result.png', items: ['Pitchfork', 'Shotgun'] },   
        { name: 'Auger', image: 'comboc_auger_result.png', items: ['Drill Motor', 'Pitchfork'] },
        { name: 'Laser Sword', image: 'comboc_lasersword_result.png', items: ['Gems', 'Flashlight'] },
        { name: 'Infernal Arms', image: 'comboc_infernalarms_result.png', items: ['Motor Oil', 'Training Sword'] },
        { name: 'Porta Mower', image: 'comboc_portamower_result.png', items: ['2x4', 'Lawn Mower'] },
        { name: 'Super B.F.G.', image: 'comboc_superbfg_result.png', items: ['Blast Frequency Gun', 'Amplifier'] },
        { name: 'Tesla Ball', image: 'comboc_teslaball_result.png', items: ['Battery', 'Bingo Ball Cage'] },
        { name: 'Spear Launcher', image: 'comboc_spearlauncher_result.png', items: ['Leaf Blower', 'Spear'] },
        { name: 'Blitzkrieg', image: 'comboc_blitzkrieg_result.png', items: ['Merc Assault Rifle', 'Wheelchair', 'Battery'] },
        { name: 'Blazing Aces', image: 'comboc_blazingace_result.png', items: ['Tennis Racquet', 'Tiki Torch'] },
        { name: 'Exsanguinator', image: 'comboc_exsanguinator_result.png', items: ['Saw Blade', 'Vacuum Cleaner'] },
        { name: 'Plate Launcher', image: 'comboc_platelauncher_result.png', items: ['Cement Saw', 'Plates'] },
        { name: 'Power Guitar', image: 'comboc_powerguitar_result.png', items: ['Amplifier', 'Electric Guitar'] },
        { name: 'Burning Skull', image: 'comboc_burningskull_result.png', items: ['Bull Skull', 'Motor Oil'] },
        { name: 'Tenderizers', image: 'comboc_tenderizers_result.png', items: ['MMA Gloves', 'Box of Nails'] },
        { name: 'Spiked Bat', image: 'comboc_spikedbat_result.png', items: ['Baseball Bat', 'Box of Nails'] },
        { name: 'Wingman', image: 'comboc_wingman_result.png', items: ['Queen', 'Nectar'] },
    ],
};